# Generated by Django 2.2.14 on 2021-05-25 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='client',
        ),
        migrations.AddField(
            model_name='offer',
            name='clients',
            field=models.ManyToManyField(related_name='_offer_clients_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
