# Generated by Django 2.2.14 on 2021-05-25 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0002_auto_20210525_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('pick_up', 'Pick up'), ('closed', 'Closed'), ('deny', 'Deny')], max_length=16),
        ),
    ]
