# Generated by Django 2.2.14 on 2021-05-25 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0003_auto_20210525_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
