# Generated by Django 2.2.14 on 2021-05-28 11:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0004_auto_20210525_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='header_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='offer',
            name='text_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
