# Generated by Django 2.2.14 on 2021-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offer', '0005_auto_20210528_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
