# Generated by Django 2.2.14 on 2021-05-27 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Deal', '0002_auto_20210526_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealfile',
            old_name='content_type',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='dealfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='DealGalleryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('archived', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=100)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Deal.Deal')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deal_gallery_file',
            },
        ),
    ]
