# Generated by Django 2.2.14 on 2021-05-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0003_auto_20210527_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='client',
        ),
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Offer.Offer'),
        ),
    ]
