# Generated by Django 2.2.14 on 2021-05-27 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0004_auto_20210527_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealfile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='dealgalleryfile',
            name='content',
        ),
    ]
