# Generated by Django 2.2.14 on 2021-05-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0005_auto_20210527_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealGalleryFile',
        ),
    ]
