# Generated by Django 2.2.14 on 2021-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0006_delete_dealgalleryfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealfile',
            name='file_type',
            field=models.CharField(choices=[('cover', 'Cover'), ('gallery', 'Gallery'), ('document', 'Document')], max_length=16, null=True),
        ),
    ]
