# Generated by Django 2.2.14 on 2021-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0007_dealfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealfile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dealfile',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
