# Generated by Django 2.2.14 on 2021-05-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationsRequest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
